/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.wasmplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.wasmplugin.psi.WasmTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Wasm.flex</tt>
 */
class WasmLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [8, 6, 7]
   * Total runtime size is 1040 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>13]|((ch>>7)&0x3f)]|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 136 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\207\100");

  /* The ZZ_CMAP_Y table has 128 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\177\200");

  /* The ZZ_CMAP_A table has 256 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\4\1\25\1\21\2\4\1\25\22\4\1\24\1\3\1\10\1\3\1\17\2\3\1\7\1\22\1\23\2\3"+
    "\1\0\3\3\1\11\1\1\1\44\1\43\1\46\1\1\1\45\3\1\1\3\1\20\5\3\6\2\24\3\1\0\1"+
    "\5\1\0\3\3\1\16\1\26\1\36\1\33\1\30\1\15\1\42\1\3\1\13\2\3\1\35\1\31\1\14"+
    "\1\32\1\27\1\3\1\37\1\40\1\6\1\34\2\3\1\12\1\41\1\3\1\0\1\3\1\0\1\3\201\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\1\1\2\5\1\1\3\1\4"+
    "\1\5\10\1\4\0\1\6\7\0\1\7\21\0\1\10"+
    "\1\11\1\0\1\12\1\13\1\0\1\14\7\0\1\15"+
    "\6\0\1\16\1\0\1\17\1\0\1\20\2\0\1\21"+
    "\3\0\1\22\3\0\1\23\2\0\1\24\5\0\1\25"+
    "\1\0\1\26\1\0\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\116\0\352"+
    "\0\u0111\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\116\0\u01fb"+
    "\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\u030c\0\u0333"+
    "\0\u035a\0\303\0\u0381\0\116\0\u03a8\0\u03cf\0\u03f6\0\u041d"+
    "\0\u0444\0\u046b\0\u0492\0\u015f\0\u04b9\0\u04e0\0\u0507\0\u052e"+
    "\0\u0555\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666"+
    "\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\116\0\116\0\u0750"+
    "\0\116\0\116\0\u0777\0\116\0\u079e\0\u07c5\0\u07ec\0\u0813"+
    "\0\u083a\0\u0861\0\u0888\0\116\0\u08af\0\u08d6\0\u08fd\0\u0924"+
    "\0\u094b\0\u0972\0\116\0\u0999\0\116\0\u09c0\0\116\0\u09e7"+
    "\0\u0a0e\0\116\0\u0a35\0\u0a5c\0\u0a83\0\116\0\u0aaa\0\u0ad1"+
    "\0\u0af8\0\116\0\u0b1f\0\u0b46\0\116\0\u0b6d\0\u0b94\0\u0bbb"+
    "\0\u0be2\0\u0c09\0\116\0\u0c30\0\116\0\u0c57\0\116\0\116"+
    "\0\116\0\116\0\116\0\116\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\4\3\1\5\1\3\1\6\1\7\1\3"+
    "\1\10\1\3\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\15\1\3\1\20\1\21\1\22\1\23\1\24"+
    "\3\3\1\25\1\26\1\3\1\27\4\4\47\3\50\0"+
    "\1\4\7\0\1\4\31\0\4\4\16\0\1\30\22\0"+
    "\1\31\5\0\4\32\1\0\1\33\2\32\1\34\10\32"+
    "\1\0\3\32\1\0\21\32\31\0\1\35\11\0\1\36"+
    "\1\0\1\37\35\0\1\40\6\0\1\41\1\0\1\42"+
    "\15\0\1\43\33\0\3\44\1\0\3\44\1\0\7\44"+
    "\6\0\21\44\20\0\1\45\47\0\1\15\2\0\2\15"+
    "\41\0\1\46\44\0\1\47\42\0\1\50\22\0\1\51"+
    "\41\0\1\52\1\0\1\53\1\0\1\54\27\0\1\55"+
    "\47\0\1\56\60\0\1\57\24\0\1\60\75\0\1\61"+
    "\37\0\1\62\47\0\1\63\20\0\2\64\3\0\3\32"+
    "\1\64\2\0\1\32\2\64\7\0\1\64\1\0\1\64"+
    "\2\0\1\64\2\0\1\64\1\32\3\0\4\64\27\0"+
    "\1\65\63\0\1\66\50\0\1\67\14\0\1\70\76\0"+
    "\1\71\50\0\1\72\41\0\1\73\5\0\21\45\1\74"+
    "\25\45\20\46\1\75\1\46\1\76\24\46\37\0\1\77"+
    "\36\0\1\100\47\0\1\101\47\0\1\102\50\0\1\103"+
    "\21\0\1\104\55\0\1\105\37\0\1\106\100\0\1\107"+
    "\24\0\1\110\62\0\1\111\51\0\1\112\41\0\1\113"+
    "\17\0\2\32\6\0\1\32\3\0\2\32\7\0\1\32"+
    "\1\0\1\32\2\0\1\32\2\0\1\32\4\0\4\32"+
    "\32\0\1\114\52\0\1\115\25\0\1\116\31\0\23\46"+
    "\1\117\43\46\1\0\26\46\16\0\1\120\62\0\1\121"+
    "\45\0\1\122\47\0\1\123\50\0\1\124\52\0\1\125"+
    "\24\0\1\126\64\0\1\127\51\0\1\130\35\0\1\131"+
    "\50\0\1\132\55\0\1\133\43\0\1\134\43\0\1\135"+
    "\54\0\1\136\46\0\1\137\44\0\1\140\41\0\1\141"+
    "\53\0\1\142\17\0\1\143\56\0\1\144\36\0\1\145"+
    "\54\0\1\146\40\0\1\147\101\0\1\150\35\0\1\151"+
    "\24\0\1\152\46\0\1\153\75\0\1\154\47\0\1\155"+
    "\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3198];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\7\1\1\11\10\1\4\0"+
    "\1\11\7\0\1\1\21\0\2\11\1\0\2\11\1\0"+
    "\1\11\7\0\1\11\6\0\1\11\1\0\1\11\1\0"+
    "\1\11\2\0\1\11\3\0\1\11\3\0\1\11\2\0"+
    "\1\11\5\0\1\11\1\0\1\11\1\0\7\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  WasmLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return TokenType.BAD_CHARACTER;
            } 
            // fall through
          case 30: break;
          case 2: 
            { return WasmTypes.TUINTEGER;
            } 
            // fall through
          case 31: break;
          case 3: 
            { return TokenType.WHITE_SPACE;
            } 
            // fall through
          case 32: break;
          case 4: 
            { return WasmTypes.TLP;
            } 
            // fall through
          case 33: break;
          case 5: 
            { return WasmTypes.TRP;
            } 
            // fall through
          case 34: break;
          case 6: 
            { return WasmTypes.TSTRING;
            } 
            // fall through
          case 35: break;
          case 7: 
            { return WasmTypes.TID;
            } 
            // fall through
          case 36: break;
          case 8: 
            { return WasmTypes.TI32;
            } 
            // fall through
          case 37: break;
          case 9: 
            { return WasmTypes.TI64;
            } 
            // fall through
          case 38: break;
          case 10: 
            { return WasmTypes.TF32;
            } 
            // fall through
          case 39: break;
          case 11: 
            { return WasmTypes.TF64;
            } 
            // fall through
          case 40: break;
          case 12: 
            { return WasmTypes.LINE_COMMENT;
            } 
            // fall through
          case 41: break;
          case 13: 
            { return WasmTypes.TMUT;
            } 
            // fall through
          case 42: break;
          case 14: 
            { return WasmTypes.TTYPE;
            } 
            // fall through
          case 43: break;
          case 15: 
            { return WasmTypes.TFUNC;
            } 
            // fall through
          case 44: break;
          case 16: 
            { return WasmTypes.BLOCK_COMMENT;
            } 
            // fall through
          case 45: break;
          case 17: 
            { return WasmTypes.TELEM;
            } 
            // fall through
          case 46: break;
          case 18: 
            { return WasmTypes.TDATA;
            } 
            // fall through
          case 47: break;
          case 19: 
            { return WasmTypes.TTABLE;
            } 
            // fall through
          case 48: break;
          case 20: 
            { return WasmTypes.TPARAM;
            } 
            // fall through
          case 49: break;
          case 21: 
            { return WasmTypes.TSTART;
            } 
            // fall through
          case 50: break;
          case 22: 
            { return WasmTypes.TIMPORT;
            } 
            // fall through
          case 51: break;
          case 23: 
            { return WasmTypes.TEXPORT;
            } 
            // fall through
          case 52: break;
          case 24: 
            { return WasmTypes.TMEMORY;
            } 
            // fall through
          case 53: break;
          case 25: 
            { return WasmTypes.TMODULE;
            } 
            // fall through
          case 54: break;
          case 26: 
            { return WasmTypes.TOFFSET;
            } 
            // fall through
          case 55: break;
          case 27: 
            { return WasmTypes.TRESULT;
            } 
            // fall through
          case 56: break;
          case 28: 
            { return WasmTypes.TGLOBAL;
            } 
            // fall through
          case 57: break;
          case 29: 
            { return WasmTypes.TANYFUNC;
            } 
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
