/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.wasmplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.wasmplugin.psi.WasmTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Wasm.flex</tt>
 */
class WasmLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [8, 6, 7]
   * Total runtime size is 1040 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>13]|((ch>>7)&0x3f)]|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 136 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\207\100");

  /* The ZZ_CMAP_Y table has 128 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\177\200");

  /* The ZZ_CMAP_A table has 256 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\5\1\33\1\27\2\5\1\33\22\5\1\32\1\4\1\11\1\4\1\25\2\4\1\10\1\30\1\31\1"+
    "\4\1\12\1\0\1\12\1\15\1\66\1\13\1\61\1\52\1\51\1\54\1\1\1\53\1\1\1\60\1\1"+
    "\1\23\1\26\1\4\1\55\3\4\4\2\1\24\1\2\11\4\1\16\12\4\1\0\1\6\1\0\1\4\1\3\1"+
    "\4\1\22\1\47\1\42\1\36\1\41\1\21\1\50\1\57\1\17\1\4\1\56\1\40\1\34\1\20\1"+
    "\35\1\43\1\65\1\44\1\45\1\7\1\37\1\64\1\63\1\14\1\46\1\62\1\0\1\4\1\0\1\4"+
    "\201\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\3\1\1\2\1\1\1\3\6\1"+
    "\1\4\1\5\1\6\14\1\1\7\1\1\1\0\1\10"+
    "\10\0\1\11\5\0\1\12\5\0\1\13\10\0\1\14"+
    "\10\0\1\15\5\0\1\16\1\0\1\17\3\0\1\7"+
    "\20\0\1\20\1\21\1\0\1\22\2\0\2\10\7\0"+
    "\1\2\1\23\1\10\1\0\1\24\1\25\1\10\1\26"+
    "\1\0\1\27\2\0\1\30\1\31\1\32\1\0\1\33"+
    "\1\0\1\34\1\35\2\0\1\36\1\37\1\0\1\40"+
    "\1\41\2\0\1\42\13\0\1\43\2\0\1\44\1\45"+
    "\3\0\1\46\13\0\1\47\2\0\1\50\16\0\1\51"+
    "\1\52\1\10\3\0\1\53\3\0\1\54\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\1\60\1\61\1\62\1\0"+
    "\1\63\1\64\2\0\1\65\1\66\1\67\3\0\1\70"+
    "\11\0\1\71\3\0\1\72\3\0\1\73\1\74\1\0"+
    "\1\75\1\76\1\0\1\77\1\0\1\100\1\0\1\101"+
    "\1\10\3\0\1\102\1\0\1\103\3\0\1\104\1\105"+
    "\5\0\1\106\3\0\1\107\2\0\1\110\4\0\1\111"+
    "\1\112\1\0\1\113\1\114\3\0\1\115\1\116\1\117"+
    "\1\0\1\120\7\0\1\121\3\0\1\122\1\123\1\124"+
    "\6\0\1\125\3\0\1\126\1\0\1\127\1\0\1\130"+
    "\1\0\1\131\3\0\1\132\1\0\1\133\6\0\1\10"+
    "\1\134\1\135\3\0\1\136\1\137\7\0\1\140\1\141"+
    "\13\0\1\142\1\143\1\144\1\145\4\0\1\146\4\0"+
    "\1\147\2\0\1\150\1\151\13\0\1\152\1\0\1\153"+
    "\5\0\1\154\10\0\1\155\1\156\1\157\1\160\1\161"+
    "\1\162\1\163\5\0\1\164\1\0\1\165\1\166\6\0"+
    "\1\167\1\170\1\171\1\172\1\173\6\0\1\174\1\175"+
    "\1\176\1\177";

  private static int [] zzUnpackAction() {
    int [] result = new int[455];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\156\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\156\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\156"+
    "\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc"+
    "\0\u07f3\0\u0113\0\u082a\0\156\0\u0861\0\u0898\0\u08cf\0\u0906"+
    "\0\u093d\0\156\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87"+
    "\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f"+
    "\0\u02cb\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\156\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1"+
    "\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432\0\u1469"+
    "\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\u16c6\0\u16fd\0\u1734\0\u176b\0\156\0\156"+
    "\0\u17a2\0\156\0\156\0\u17d9\0\156\0\u1810\0\156\0\u1847"+
    "\0\u187e\0\156\0\156\0\156\0\u18b5\0\156\0\u18ec\0\156"+
    "\0\156\0\u1923\0\u195a\0\156\0\156\0\u1991\0\156\0\156"+
    "\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4\0\u1adb\0\u1b12\0\u1b49"+
    "\0\u1b80\0\u1bb7\0\u1bee\0\u1c25\0\u1c5c\0\u1c93\0\156\0\u1cca"+
    "\0\u1d01\0\156\0\156\0\u1d38\0\u1d6f\0\u1da6\0\156\0\u1ddd"+
    "\0\u1e14\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95"+
    "\0\u1fcc\0\u2003\0\156\0\u203a\0\u2071\0\156\0\u20a8\0\u20df"+
    "\0\u2116\0\u214d\0\u2184\0\u21bb\0\u21f2\0\u2229\0\u2260\0\u2297"+
    "\0\u22ce\0\u2305\0\u233c\0\u2373\0\156\0\156\0\u23aa\0\u23e1"+
    "\0\u2418\0\u244f\0\156\0\u2486\0\u24bd\0\u24f4\0\156\0\u252b"+
    "\0\u2562\0\u2599\0\u25d0\0\156\0\u2607\0\156\0\u263e\0\156"+
    "\0\156\0\u2675\0\156\0\u26ac\0\156\0\156\0\u26e3\0\u271a"+
    "\0\156\0\156\0\u2751\0\u2788\0\u27bf\0\u27f6\0\156\0\u282d"+
    "\0\u2864\0\u289b\0\u28d2\0\u2909\0\u2940\0\u2977\0\u29ae\0\u29e5"+
    "\0\156\0\u2a1c\0\u2a53\0\u2a8a\0\156\0\u2ac1\0\u2af8\0\u2b2f"+
    "\0\156\0\156\0\u2b66\0\156\0\156\0\u2b9d\0\156\0\u2bd4"+
    "\0\156\0\u2c0b\0\u2c42\0\u2c79\0\u2cb0\0\u2ce7\0\u2d1e\0\156"+
    "\0\u2d55\0\156\0\u2d8c\0\u2dc3\0\u2dfa\0\156\0\156\0\u2e31"+
    "\0\u2e68\0\u2e9f\0\u2ed6\0\u2f0d\0\156\0\u2f44\0\u2f7b\0\u2fb2"+
    "\0\156\0\u2fe9\0\u3020\0\156\0\u3057\0\u308e\0\u30c5\0\u30fc"+
    "\0\156\0\156\0\u3133\0\156\0\u316a\0\u31a1\0\u31d8\0\u320f"+
    "\0\156\0\156\0\156\0\u3246\0\156\0\u327d\0\u32b4\0\u32eb"+
    "\0\u3322\0\u3359\0\u3390\0\u33c7\0\156\0\u33fe\0\u3435\0\u346c"+
    "\0\156\0\156\0\156\0\u34a3\0\u34da\0\u3511\0\u3548\0\u357f"+
    "\0\u35b6\0\156\0\u35ed\0\u3624\0\u365b\0\156\0\u3692\0\156"+
    "\0\u36c9\0\156\0\u3700\0\156\0\u3737\0\u376e\0\u37a5\0\156"+
    "\0\u37dc\0\156\0\u3813\0\u384a\0\u3881\0\u38b8\0\u38ef\0\u3926"+
    "\0\u395d\0\156\0\156\0\u3994\0\u39cb\0\u3a02\0\156\0\156"+
    "\0\u3a39\0\u3a70\0\u3aa7\0\u3ade\0\u3b15\0\u3b4c\0\u3b83\0\156"+
    "\0\156\0\u3bba\0\u3bf1\0\u3c28\0\u3c5f\0\u3c96\0\u3ccd\0\u3d04"+
    "\0\u3d3b\0\u3d72\0\u3da9\0\u3de0\0\156\0\156\0\156\0\156"+
    "\0\u3e17\0\u3e4e\0\u3e85\0\u3ebc\0\156\0\u3ef3\0\u3f2a\0\u3f61"+
    "\0\u3f98\0\156\0\u3fcf\0\u4006\0\156\0\156\0\u403d\0\u4074"+
    "\0\u40ab\0\u40e2\0\u4119\0\u4150\0\u4187\0\u41be\0\u41f5\0\u422c"+
    "\0\u4263\0\156\0\u429a\0\156\0\u42d1\0\u4308\0\u433f\0\u4376"+
    "\0\u43ad\0\156\0\u43e4\0\u441b\0\u4452\0\u4489\0\u44c0\0\u44f7"+
    "\0\u452e\0\u4565\0\156\0\156\0\156\0\156\0\156\0\156"+
    "\0\156\0\u459c\0\u45d3\0\u460a\0\u4641\0\u4678\0\156\0\u46af"+
    "\0\156\0\156\0\u46e6\0\u471d\0\u4754\0\u478b\0\u47c2\0\u47f9"+
    "\0\156\0\156\0\156\0\156\0\156\0\u4830\0\u4867\0\u489e"+
    "\0\u48d5\0\u490c\0\u4943\0\156\0\156\0\156\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[455];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\5\3\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\3\1\13\1\14\1\15\1\16\2\3"+
    "\1\17\1\20\1\21\1\22\1\23\2\21\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\3\1\36\1\37\4\4\1\40\2\3\2\4\1\3"+
    "\1\41\72\3\70\0\1\4\1\0\1\42\7\0\1\4"+
    "\1\0\1\43\6\0\1\44\14\0\1\44\7\0\4\4"+
    "\3\0\2\4\27\0\1\45\16\0\1\46\2\0\1\47"+
    "\1\0\1\50\10\0\1\51\7\0\5\52\1\0\1\53"+
    "\2\52\1\54\15\52\1\0\3\52\1\0\33\52\1\0"+
    "\1\4\11\0\1\10\3\0\1\55\1\56\30\0\4\4"+
    "\3\0\2\4\6\0\1\4\1\0\1\42\7\0\1\4"+
    "\1\57\1\43\6\0\1\44\14\0\1\44\7\0\4\4"+
    "\3\0\2\4\42\0\1\60\51\0\1\61\1\62\12\0"+
    "\1\63\14\0\1\64\1\0\1\65\35\0\1\66\12\0"+
    "\1\67\3\0\1\70\64\0\1\71\1\72\10\0\1\73"+
    "\1\0\1\74\33\0\1\75\15\0\1\76\1\0\1\77"+
    "\6\0\1\100\20\0\4\101\1\0\3\101\1\0\14\101"+
    "\6\0\33\101\26\0\1\102\67\0\1\21\2\0\2\21"+
    "\61\0\1\103\57\0\1\104\2\0\1\105\12\0\1\106"+
    "\1\0\1\107\1\0\1\110\46\0\1\111\22\0\1\112"+
    "\41\0\1\113\2\0\1\114\16\0\1\115\2\0\1\116"+
    "\42\0\1\117\55\0\1\120\25\0\1\121\3\0\1\122"+
    "\41\0\1\123\3\0\1\124\17\0\1\125\24\0\1\126"+
    "\10\0\1\127\12\0\1\130\12\0\1\131\2\0\1\132"+
    "\1\133\47\0\1\134\12\0\1\135\6\0\1\136\63\0"+
    "\1\137\34\0\1\140\7\0\1\141\17\0\1\142\1\0"+
    "\1\143\15\0\1\144\5\0\1\145\41\0\1\146\3\0"+
    "\1\147\31\0\1\150\30\0\1\151\1\152\2\0\1\153"+
    "\66\0\1\154\23\0\1\4\11\0\1\4\35\0\4\4"+
    "\3\0\2\4\6\0\1\155\11\0\1\155\10\0\1\44"+
    "\14\0\1\44\7\0\4\155\3\0\2\155\6\0\1\156"+
    "\10\0\1\157\1\156\35\0\4\156\3\0\2\156\54\0"+
    "\1\160\60\0\1\161\64\0\1\162\72\0\1\163\64\0"+
    "\1\164\26\0\2\165\4\0\3\52\1\0\1\165\4\0"+
    "\1\52\2\165\1\0\1\165\11\0\1\165\2\0\2\165"+
    "\1\0\1\52\2\0\1\165\1\0\4\165\3\0\2\165"+
    "\25\0\1\61\70\0\1\66\45\0\2\166\10\0\1\166"+
    "\5\0\2\166\1\0\1\166\11\0\1\166\2\0\2\166"+
    "\4\0\1\166\1\0\4\166\3\0\2\166\51\0\1\167"+
    "\43\0\1\170\110\0\1\171\75\0\1\172\70\0\1\173"+
    "\32\0\1\174\111\0\1\175\45\0\1\176\25\0\1\177"+
    "\36\0\1\200\103\0\1\201\103\0\1\202\70\0\1\203"+
    "\50\0\1\204\7\0\1\205\56\0\1\206\47\0\1\207"+
    "\114\0\1\210\21\0\27\102\1\211\37\102\26\103\1\212"+
    "\1\103\1\213\36\103\20\0\1\214\62\0\1\215\110\0"+
    "\1\216\37\0\1\217\30\0\1\220\62\0\1\221\53\0"+
    "\1\222\131\0\1\223\11\0\1\224\113\0\1\225\67\0"+
    "\1\226\75\0\1\227\25\0\1\230\105\0\1\231\12\0"+
    "\1\232\4\0\1\233\27\0\1\234\72\0\1\235\33\0"+
    "\1\236\61\0\1\237\71\0\1\240\3\0\1\241\103\0"+
    "\1\242\66\0\1\243\44\0\1\244\46\0\1\245\22\0"+
    "\1\246\105\0\1\247\23\0\1\250\113\0\1\251\65\0"+
    "\1\252\60\0\1\253\40\0\1\254\7\0\1\255\14\0"+
    "\1\256\10\0\1\257\43\0\1\260\12\0\1\261\113\0"+
    "\1\262\53\0\1\263\26\0\1\264\30\0\1\265\66\0"+
    "\1\266\3\0\1\267\66\0\1\270\57\0\1\271\34\0"+
    "\1\272\66\0\1\273\120\0\1\274\34\0\1\275\3\0"+
    "\1\276\114\0\1\277\53\0\1\300\45\0\1\155\1\0"+
    "\1\301\7\0\1\155\10\0\1\44\14\0\1\44\7\0"+
    "\4\155\3\0\2\155\6\0\1\156\1\0\1\157\7\0"+
    "\1\156\35\0\4\156\3\0\2\156\6\0\1\156\11\0"+
    "\1\156\35\0\4\156\3\0\2\156\45\0\1\302\31\0"+
    "\1\303\103\0\1\304\107\0\1\305\45\0\1\306\47\0"+
    "\2\52\10\0\1\52\5\0\2\52\1\0\1\52\11\0"+
    "\1\52\2\0\2\52\4\0\1\52\1\0\4\52\3\0"+
    "\2\52\6\0\2\166\1\57\7\0\1\166\1\0\1\307"+
    "\1\44\2\0\2\166\1\0\1\166\11\0\1\166\2\0"+
    "\2\166\1\44\3\0\1\166\1\0\4\166\3\0\2\166"+
    "\42\0\1\310\54\0\1\311\107\0\1\312\64\0\1\313"+
    "\61\0\1\314\52\0\1\315\115\0\1\316\16\0\31\103"+
    "\1\317\63\103\1\0\40\103\37\0\1\320\64\0\1\321"+
    "\76\0\1\322\24\0\1\323\105\0\1\324\101\0\1\325"+
    "\74\0\1\326\64\0\1\327\64\0\1\330\5\0\1\331"+
    "\57\0\1\332\73\0\1\333\45\0\1\334\103\0\1\335"+
    "\5\0\1\336\62\0\1\337\62\0\1\340\65\0\1\341"+
    "\73\0\1\342\65\0\1\343\73\0\1\344\16\0\1\345"+
    "\50\0\1\346\60\0\1\347\50\0\1\350\106\0\1\351"+
    "\60\0\1\352\71\0\1\353\47\0\1\354\51\0\1\355"+
    "\122\0\1\356\73\0\1\357\66\0\1\360\63\0\1\361"+
    "\30\0\1\362\124\0\1\363\30\0\1\364\72\0\1\365"+
    "\121\0\1\366\33\0\1\367\7\0\1\370\106\0\1\371"+
    "\5\0\1\372\70\0\1\373\56\0\1\374\5\0\1\375"+
    "\24\0\1\376\146\0\1\377\46\0\1\u0100\24\0\1\155"+
    "\11\0\1\155\35\0\4\155\3\0\2\155\46\0\1\u0101"+
    "\65\0\1\u0102\70\0\1\u0103\25\0\2\u0104\10\0\1\u0104"+
    "\2\0\1\44\2\0\2\u0104\1\0\1\u0104\11\0\1\u0104"+
    "\2\0\2\u0104\1\44\3\0\1\u0104\1\0\4\u0104\3\0"+
    "\2\u0104\51\0\1\u0105\35\0\1\u0106\114\0\1\u0107\71\0"+
    "\1\u0108\61\0\1\u0109\47\0\1\u010a\106\0\1\u010b\72\0"+
    "\1\u010c\63\0\1\u010d\64\0\1\u010e\5\0\1\u010f\30\0"+
    "\1\u0110\101\0\1\u0111\115\0\1\u0112\6\0\1\u0113\1\u0114"+
    "\45\0\1\u0115\46\0\1\u0116\112\0\1\u0117\25\0\1\u0118"+
    "\72\0\1\u0119\120\0\1\u011a\72\0\1\u011b\55\0\1\u011c"+
    "\52\0\1\u011d\103\0\1\u011e\75\0\1\u011f\31\0\1\u0120"+
    "\116\0\1\u0121\5\0\1\u0122\61\0\1\u0123\35\0\1\u0124"+
    "\120\0\1\u0125\65\0\1\u0126\7\0\1\u0127\60\0\1\u0128"+
    "\63\0\1\u0129\5\0\1\u012a\77\0\1\u012b\32\0\1\u012c"+
    "\65\0\1\u012d\67\0\1\u012e\104\0\1\u012f\7\0\1\u0130"+
    "\104\0\1\u0131\35\0\1\u0132\34\0\1\u0133\64\0\2\u0104"+
    "\1\u0134\7\0\1\u0104\2\0\1\44\2\0\2\u0104\1\0"+
    "\1\u0104\11\0\1\u0104\2\0\2\u0104\1\44\3\0\1\u0104"+
    "\1\0\4\u0104\3\0\2\u0104\14\0\1\u0135\73\0\1\u0136"+
    "\117\0\1\u0137\41\0\1\u0138\107\0\1\u0139\73\0\1\u013a"+
    "\27\0\1\u013b\120\0\1\u013c\67\0\1\u013d\76\0\1\u013e"+
    "\17\0\1\u013f\136\0\1\u0140\51\0\1\u0141\37\0\1\u0142"+
    "\76\0\1\u0143\113\0\1\u0144\41\0\1\u0145\56\0\1\u0146"+
    "\66\0\1\u0147\77\0\1\u0148\107\0\1\u0149\34\0\1\u014a"+
    "\130\0\1\u014b\6\0\1\u014c\1\u014d\42\0\1\u014e\71\0"+
    "\1\u014f\35\0\1\u0150\126\0\1\u0151\57\0\1\u0152\63\0"+
    "\1\u0153\71\0\1\u0154\45\0\1\u0155\111\0\1\u0156\63\0"+
    "\1\u0157\5\0\1\u0158\22\0\2\u0104\10\0\1\u0104\5\0"+
    "\2\u0104\1\0\1\u0104\11\0\1\u0104\2\0\2\u0104\4\0"+
    "\1\u0104\1\0\4\u0104\3\0\2\u0104\6\0\2\u0159\10\0"+
    "\1\u0159\5\0\2\u0159\1\0\1\u0159\11\0\1\u0159\2\0"+
    "\2\u0159\4\0\1\u0159\1\0\4\u0159\3\0\2\u0159\14\0"+
    "\1\u015a\121\0\1\u015b\112\0\1\u015c\57\0\1\u015d\12\0"+
    "\1\u015e\122\0\1\u015f\5\0\1\u0160\24\0\1\u0161\66\0"+
    "\1\u0162\103\0\1\u0163\55\0\1\u0164\127\0\1\u0165\57\0"+
    "\1\u0166\71\0\1\u0167\74\0\1\u0168\67\0\1\u0169\55\0"+
    "\1\u016a\61\0\1\u016b\71\0\1\u016c\70\0\1\u016d\61\0"+
    "\1\u016e\104\0\1\u016f\35\0\1\u0170\132\0\1\u0171\66\0"+
    "\1\u0172\1\0\2\u0159\1\u0136\7\0\1\u0159\5\0\2\u0159"+
    "\1\0\1\u0159\11\0\1\u0159\2\0\2\u0159\4\0\1\u0159"+
    "\1\0\4\u0159\3\0\2\u0159\26\0\1\u0173\67\0\1\u0174"+
    "\103\0\1\u0175\5\0\1\u0176\60\0\1\u0177\5\0\1\u0178"+
    "\60\0\1\u0179\5\0\1\u017a\57\0\1\u017b\33\0\1\u017c"+
    "\103\0\1\u017d\134\0\1\u017e\43\0\1\u017f\45\0\1\u0180"+
    "\113\0\1\u0181\60\0\1\u0182\47\0\1\u0183\113\0\1\u0184"+
    "\73\0\1\u0185\52\0\1\u0186\47\0\1\u0187\66\0\1\u0188"+
    "\120\0\1\u0189\62\0\1\u018a\105\0\1\u018b\66\0\1\u018c"+
    "\17\0\1\u018d\106\0\1\u018e\5\0\1\u018f\42\0\1\u0190"+
    "\111\0\1\u0191\62\0\1\u0192\50\0\1\u0193\104\0\1\u0194"+
    "\50\0\1\u0195\115\0\1\u0196\1\0\1\u0197\64\0\1\u0198"+
    "\1\0\1\u0199\67\0\1\u019a\52\0\1\u019b\45\0\1\u019c"+
    "\66\0\1\u019d\113\0\1\u019e\110\0\1\u019f\66\0\1\u01a0"+
    "\51\0\1\u01a1\56\0\1\u01a2\65\0\1\u01a3\66\0\1\u01a4"+
    "\100\0\1\u01a5\70\0\1\u01a6\64\0\1\u01a7\70\0\1\u01a8"+
    "\53\0\1\u01a9\76\0\1\u01aa\66\0\1\u01ab\56\0\1\u01ac"+
    "\44\0\1\u01ad\66\0\1\u01ae\121\0\1\u01af\23\0\1\u01b0"+
    "\131\0\1\u01b1\66\0\1\u01b2\56\0\1\u01b3\75\0\1\u01b4"+
    "\1\0\1\u01b5\64\0\1\u01b6\1\0\1\u01b7\101\0\1\u01b8"+
    "\7\0\1\u01b9\131\0\1\u01ba\70\0\1\u01bb\64\0\1\u01bc"+
    "\70\0\1\u01bd\31\0\1\u01be\1\0\1\u01bf\116\0\1\u01c0"+
    "\1\0\1\u01c1\64\0\1\u01c2\1\0\1\u01c3\65\0\1\u01c4"+
    "\70\0\1\u01c5\64\0\1\u01c6\70\0\1\u01c7\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[18810];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\1\11\10\1\1\11\14\1\1\11"+
    "\1\1\1\0\1\1\10\0\1\11\5\0\1\11\5\0"+
    "\1\1\10\0\1\1\10\0\1\11\5\0\1\1\1\0"+
    "\1\1\3\0\1\1\20\0\2\1\1\0\1\1\2\0"+
    "\2\1\7\0\1\1\2\11\1\0\2\11\1\1\1\11"+
    "\1\0\1\11\2\0\3\11\1\0\1\11\1\0\2\11"+
    "\2\0\2\11\1\0\2\11\2\0\1\1\13\0\1\11"+
    "\2\0\2\11\3\0\1\11\13\0\1\11\2\0\1\11"+
    "\16\0\2\11\1\1\3\0\1\11\3\0\1\11\4\0"+
    "\1\11\1\0\1\11\1\0\2\11\1\1\1\11\1\0"+
    "\2\11\2\0\2\11\1\1\3\0\1\11\11\0\1\11"+
    "\3\0\1\11\3\0\2\11\1\0\2\11\1\0\1\11"+
    "\1\0\1\11\1\0\2\1\3\0\1\11\1\0\1\11"+
    "\3\0\2\11\5\0\1\11\3\0\1\11\2\0\1\11"+
    "\4\0\2\11\1\0\1\11\1\1\3\0\3\11\1\0"+
    "\1\11\7\0\1\11\3\0\3\11\6\0\1\11\3\0"+
    "\1\11\1\0\1\11\1\0\1\11\1\0\1\11\3\0"+
    "\1\11\1\0\1\11\6\0\1\1\2\11\3\0\2\11"+
    "\7\0\2\11\13\0\4\11\4\0\1\11\4\0\1\11"+
    "\2\0\2\11\13\0\1\11\1\0\1\11\5\0\1\11"+
    "\10\0\7\11\5\0\1\11\1\0\2\11\6\0\5\11"+
    "\6\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[455];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  WasmLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return TokenType.BAD_CHARACTER;
            } 
            // fall through
          case 128: break;
          case 2: 
            { return WasmTypes.TINT;
            } 
            // fall through
          case 129: break;
          case 3: 
            { return WasmTypes.TDOT;
            } 
            // fall through
          case 130: break;
          case 4: 
            { return TokenType.WHITE_SPACE;
            } 
            // fall through
          case 131: break;
          case 5: 
            { return WasmTypes.TLP;
            } 
            // fall through
          case 132: break;
          case 6: 
            { return WasmTypes.TRP;
            } 
            // fall through
          case 133: break;
          case 7: 
            { return WasmTypes.TEQ;
            } 
            // fall through
          case 134: break;
          case 8: 
            { return WasmTypes.TFLOAT;
            } 
            // fall through
          case 135: break;
          case 9: 
            { return WasmTypes.TNAME;
            } 
            // fall through
          case 136: break;
          case 10: 
            { return WasmTypes.TIF;
            } 
            // fall through
          case 137: break;
          case 11: 
            { return WasmTypes.TNE;
            } 
            // fall through
          case 138: break;
          case 12: 
            { return WasmTypes.TID;
            } 
            // fall through
          case 139: break;
          case 13: 
            { return WasmTypes.TOR;
            } 
            // fall through
          case 140: break;
          case 14: 
            { return WasmTypes.TLT;
            } 
            // fall through
          case 141: break;
          case 15: 
            { return WasmTypes.TLE;
            } 
            // fall through
          case 142: break;
          case 16: 
            { return WasmTypes.TBR;
            } 
            // fall through
          case 143: break;
          case 17: 
            { return WasmTypes.TGT;
            } 
            // fall through
          case 144: break;
          case 18: 
            { return WasmTypes.TGE;
            } 
            // fall through
          case 145: break;
          case 19: 
            { return WasmTypes.TXOR;
            } 
            // fall through
          case 146: break;
          case 20: 
            { return WasmTypes.TI32;
            } 
            // fall through
          case 147: break;
          case 21: 
            { return WasmTypes.TI64;
            } 
            // fall through
          case 148: break;
          case 22: 
            { return WasmTypes.TNOP;
            } 
            // fall through
          case 149: break;
          case 23: 
            { return WasmTypes.TNEG;
            } 
            // fall through
          case 150: break;
          case 24: 
            { return WasmTypes.TF32;
            } 
            // fall through
          case 151: break;
          case 25: 
            { return WasmTypes.TF64;
            } 
            // fall through
          case 152: break;
          case 26: 
            { return WasmTypes.TAND;
            } 
            // fall through
          case 153: break;
          case 27: 
            { return WasmTypes.TADD;
            } 
            // fall through
          case 154: break;
          case 28: 
            { return WasmTypes.TABS;
            } 
            // fall through
          case 155: break;
          case 29: 
            { return WasmTypes.LINE_COMMENT;
            } 
            // fall through
          case 156: break;
          case 30: 
            { return WasmTypes.TMIN;
            } 
            // fall through
          case 157: break;
          case 31: 
            { return WasmTypes.TMAX;
            } 
            // fall through
          case 158: break;
          case 32: 
            { return WasmTypes.TMUT;
            } 
            // fall through
          case 159: break;
          case 33: 
            { return WasmTypes.TMUL;
            } 
            // fall through
          case 160: break;
          case 34: 
            { return WasmTypes.TDIV;
            } 
            // fall through
          case 161: break;
          case 35: 
            { return WasmTypes.TEND;
            } 
            // fall through
          case 162: break;
          case 36: 
            { return WasmTypes.TEQZ;
            } 
            // fall through
          case 163: break;
          case 37: 
            { return WasmTypes.TCTZ;
            } 
            // fall through
          case 164: break;
          case 38: 
            { return WasmTypes.TCLZ;
            } 
            // fall through
          case 165: break;
          case 39: 
            { return WasmTypes.TSUB;
            } 
            // fall through
          case 166: break;
          case 40: 
            { return WasmTypes.TSHL;
            } 
            // fall through
          case 167: break;
          case 41: 
            { return WasmTypes.TTYPE;
            } 
            // fall through
          case 168: break;
          case 42: 
            { return WasmTypes.TTHEN;
            } 
            // fall through
          case 169: break;
          case 43: 
            { return WasmTypes.TFUNC;
            } 
            // fall through
          case 170: break;
          case 44: 
            { return WasmTypes.BLOCK_COMMENT;
            } 
            // fall through
          case 171: break;
          case 45: 
            { return WasmTypes.TDATA;
            } 
            // fall through
          case 172: break;
          case 46: 
            { return WasmTypes.TDROP;
            } 
            // fall through
          case 173: break;
          case 47: 
            { return WasmTypes.TLT_U;
            } 
            // fall through
          case 174: break;
          case 48: 
            { return WasmTypes.TLT_S;
            } 
            // fall through
          case 175: break;
          case 49: 
            { return WasmTypes.TLOAD;
            } 
            // fall through
          case 176: break;
          case 50: 
            { return WasmTypes.TLOOP;
            } 
            // fall through
          case 177: break;
          case 51: 
            { return WasmTypes.TLE_U;
            } 
            // fall through
          case 178: break;
          case 52: 
            { return WasmTypes.TLE_S;
            } 
            // fall through
          case 179: break;
          case 53: 
            { return WasmTypes.TELEM;
            } 
            // fall through
          case 180: break;
          case 54: 
            { return WasmTypes.TELSE;
            } 
            // fall through
          case 181: break;
          case 55: 
            { return WasmTypes.TCALL;
            } 
            // fall through
          case 182: break;
          case 56: 
            { return WasmTypes.TCEIL;
            } 
            // fall through
          case 183: break;
          case 57: 
            { return WasmTypes.TSIZE;
            } 
            // fall through
          case 184: break;
          case 58: 
            { return WasmTypes.TSQRT;
            } 
            // fall through
          case 185: break;
          case 59: 
            { return WasmTypes.TGT_U;
            } 
            // fall through
          case 186: break;
          case 60: 
            { return WasmTypes.TGT_S;
            } 
            // fall through
          case 187: break;
          case 61: 
            { return WasmTypes.TGE_U;
            } 
            // fall through
          case 188: break;
          case 62: 
            { return WasmTypes.TGE_S;
            } 
            // fall through
          case 189: break;
          case 63: 
            { return WasmTypes.TGROW;
            } 
            // fall through
          case 190: break;
          case 64: 
            { return WasmTypes.TTABLE;
            } 
            // fall through
          case 191: break;
          case 65: 
            { return WasmTypes.TTRUNC;
            } 
            // fall through
          case 192: break;
          case 66: 
            { return WasmTypes.TFLOOR;
            } 
            // fall through
          case 193: break;
          case 67: 
            { return WasmTypes.TALIGN;
            } 
            // fall through
          case 194: break;
          case 68: 
            { return WasmTypes.TDIV_U;
            } 
            // fall through
          case 195: break;
          case 69: 
            { return WasmTypes.TDIV_S;
            } 
            // fall through
          case 196: break;
          case 70: 
            { return WasmTypes.TLOCAL;
            } 
            // fall through
          case 197: break;
          case 71: 
            { return WasmTypes.TCONST;
            } 
            // fall through
          case 198: break;
          case 72: 
            { return WasmTypes.TPARAM;
            } 
            // fall through
          case 199: break;
          case 73: 
            { return WasmTypes.TREM_U;
            } 
            // fall through
          case 200: break;
          case 74: 
            { return WasmTypes.TREM_S;
            } 
            // fall through
          case 201: break;
          case 75: 
            { return WasmTypes.TSTART;
            } 
            // fall through
          case 202: break;
          case 76: 
            { return WasmTypes.TSTORE;
            } 
            // fall through
          case 203: break;
          case 77: 
            { return WasmTypes.TSHR_U;
            } 
            // fall through
          case 204: break;
          case 78: 
            { return WasmTypes.TSHR_S;
            } 
            // fall through
          case 205: break;
          case 79: 
            { return WasmTypes.TBLOCK;
            } 
            // fall through
          case 206: break;
          case 80: 
            { return WasmTypes.TBR_IF;
            } 
            // fall through
          case 207: break;
          case 81: 
            { return WasmTypes.TIMPORT;
            } 
            // fall through
          case 208: break;
          case 82: 
            { return WasmTypes.TMODULE;
            } 
            // fall through
          case 209: break;
          case 83: 
            { return WasmTypes.TMEMORY;
            } 
            // fall through
          case 210: break;
          case 84: 
            { return WasmTypes.TOFFSET;
            } 
            // fall through
          case 211: break;
          case 85: 
            { return WasmTypes.TEXPORT;
            } 
            // fall through
          case 212: break;
          case 86: 
            { return WasmTypes.TPOPCNT;
            } 
            // fall through
          case 213: break;
          case 87: 
            { return WasmTypes.TRETURN;
            } 
            // fall through
          case 214: break;
          case 88: 
            { return WasmTypes.TRESULT;
            } 
            // fall through
          case 215: break;
          case 89: 
            { return WasmTypes.TSTORE8;
            } 
            // fall through
          case 216: break;
          case 90: 
            { return WasmTypes.TSELECT;
            } 
            // fall through
          case 217: break;
          case 91: 
            { return WasmTypes.TGLOBAL;
            } 
            // fall through
          case 218: break;
          case 92: 
            { return WasmTypes.TNEAREST;
            } 
            // fall through
          case 219: break;
          case 93: 
            { return WasmTypes.TANYFUNC;
            } 
            // fall through
          case 220: break;
          case 94: 
            { return WasmTypes.TLOAD8_U;
            } 
            // fall through
          case 221: break;
          case 95: 
            { return WasmTypes.TLOAD8_S;
            } 
            // fall through
          case 222: break;
          case 96: 
            { return WasmTypes.TSTORE32;
            } 
            // fall through
          case 223: break;
          case 97: 
            { return WasmTypes.TSTORE16;
            } 
            // fall through
          case 224: break;
          case 98: 
            { return WasmTypes.TLOAD32_U;
            } 
            // fall through
          case 225: break;
          case 99: 
            { return WasmTypes.TLOAD32_S;
            } 
            // fall through
          case 226: break;
          case 100: 
            { return WasmTypes.TLOAD16_U;
            } 
            // fall through
          case 227: break;
          case 101: 
            { return WasmTypes.TLOAD16_S;
            } 
            // fall through
          case 228: break;
          case 102: 
            { return WasmTypes.TCOPYSIGN;
            } 
            // fall through
          case 229: break;
          case 103: 
            { return WasmTypes.TBR_TABLE;
            } 
            // fall through
          case 230: break;
          case 104: 
            { return WasmTypes.TWRAP_I64;
            } 
            // fall through
          case 231: break;
          case 105: 
            { return WasmTypes.TTEE_GLOBAL;
            } 
            // fall through
          case 232: break;
          case 106: 
            { return WasmTypes.TSET_LOCAL;
            } 
            // fall through
          case 233: break;
          case 107: 
            { return WasmTypes.TGET_LOCAL;
            } 
            // fall through
          case 234: break;
          case 108: 
            { return WasmTypes.TDEMOTE_F64;
            } 
            // fall through
          case 235: break;
          case 109: 
            { return WasmTypes.TSET_GLOBAL;
            } 
            // fall through
          case 236: break;
          case 110: 
            { return WasmTypes.TGET_GLOBAL;
            } 
            // fall through
          case 237: break;
          case 111: 
            { return WasmTypes.TTRUNC_U_F32;
            } 
            // fall through
          case 238: break;
          case 112: 
            { return WasmTypes.TTRUNC_U_F64;
            } 
            // fall through
          case 239: break;
          case 113: 
            { return WasmTypes.TTRUNC_S_F32;
            } 
            // fall through
          case 240: break;
          case 114: 
            { return WasmTypes.TTRUNC_S_F64;
            } 
            // fall through
          case 241: break;
          case 115: 
            { return WasmTypes.TUNREACHABLE;
            } 
            // fall through
          case 242: break;
          case 116: 
            { return WasmTypes.TPROMOTE_F32;
            } 
            // fall through
          case 243: break;
          case 117: 
            { return WasmTypes.TEXTEND_U_I32;
            } 
            // fall through
          case 244: break;
          case 118: 
            { return WasmTypes.TEXTEND_S_I32;
            } 
            // fall through
          case 245: break;
          case 119: 
            { return WasmTypes.TCALL_INDIRECT;
            } 
            // fall through
          case 246: break;
          case 120: 
            { return WasmTypes.TCONVERT_U_I32;
            } 
            // fall through
          case 247: break;
          case 121: 
            { return WasmTypes.TCONVERT_U_I64;
            } 
            // fall through
          case 248: break;
          case 122: 
            { return WasmTypes.TCONVERT_S_I32;
            } 
            // fall through
          case 249: break;
          case 123: 
            { return WasmTypes.TCONVERT_S_I64;
            } 
            // fall through
          case 250: break;
          case 124: 
            { return WasmTypes.TREINTERPRET_I32;
            } 
            // fall through
          case 251: break;
          case 125: 
            { return WasmTypes.TREINTERPRET_I64;
            } 
            // fall through
          case 252: break;
          case 126: 
            { return WasmTypes.TREINTERPRET_F32;
            } 
            // fall through
          case 253: break;
          case 127: 
            { return WasmTypes.TREINTERPRET_F64;
            } 
            // fall through
          case 254: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
